language: java

jdk: 
  - oraclejdk8
  
before install:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER

deploy:
  deploy: heroku
  api_key:
    secure: ef7e4ee0-9994-48c2-af2f-b8bb4971b626

addons:
  sonarcloud:
    organization: "singham8659-github" # the key of the org you chose at step #3
    token:
      secure: $HEROKU_API_KEY # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
  - docker build -t petclic:$TRAVIS_BUILD_NUMBER

jobs:
  include:
    - stage: quality
      script:
        - sonar-scanner
    - stage: deploy
      script:
        - curl https://cli-assets.heroku.com/install.sh | sh
        - heroku --version
        - heroku container:login
        - heroku container:push web --app igci-petclinic
        - heroku container:release web --app igci-petclinic
        
